GET http://localhost:3000/api/plants

###

GET http://localhost:3000/api/plants/:id

###

POST http://localhost:3000/api/plants
Content-Type: application/json

###

PUT http://localhost:3000/api/plants

###

DELETE http://localhost:3000/api/plants